package dev.wizishan.stonks.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import java.time.LocalDate

/**
 * A single logged expense. [amountMinor] is a count of minor units — 8250 means €82.50
 * (see [dev.wizishan.stonks.core.Money]).
 *
 * Delete behaviour is deliberate:
 * - **Category is RESTRICT.** Deleting a category that still has expenses would either
 *   destroy history or leave rows with no category, so the database refuses and the UI
 *   has to make the user reassign first.
 * - **Trip is SET_NULL.** A trip is only a grouping tag; deleting "Japan 2026" should
 *   leave the expenses in place as ordinary daily spend.
 */
@Entity(
    tableName = "expenses",
    foreignKeys = [
        ForeignKey(
            entity = Category::class,
            parentColumns = ["id"],
            childColumns = ["categoryId"],
            onDelete = ForeignKey.RESTRICT,
        ),
        ForeignKey(
            entity = Trip::class,
            parentColumns = ["id"],
            childColumns = ["tripId"],
            onDelete = ForeignKey.SET_NULL,
        ),
    ],
    indices = [Index("categoryId"), Index("tripId"), Index("date")],
)
data class Expense(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val amountMinor: Long,
    val date: LocalDate,
    val categoryId: Long,
    val tripId: Long? = null,
    val note: String? = null,
    /**
     * Set when this row was generated by a recurring rule.
     *
     * The column exists from version 1 so the export format never has to change shape,
     * but the foreign key to `recurring_rules` is added with that table in milestone 6 —
     * a constraint pointing at a table that does not exist yet would not build.
     */
    val recurringRuleId: Long? = null,
)
